name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - "breaking"
  minor:
    labels:
      - "enhancement"
  default: "patch"
template: |
  ## Changes
  $CHANGES
initial-version: '1.0.0'
