name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: 🛠 Checkout code
        uses: actions/checkout@v3

      - name: 🧪 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: 📦 Install actionlint
        run: |
          curl -sL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash | bash

      - name: 🔎 Validate GitHub Actions workflows
        run: ./actionlint -color
        
      - name: 📦 Install yamllint
        run: pip install yamllint
        
      - name: 🔎 Validate YAML syntax
        run: yamllint -c .github/yamllint-config.yml .
